# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ""

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
  - { icon: "github", link: "https://github.com/daqnext"}
  - { icon: "twitter", link: "https://twitter.com/NetworkMeson"}
  - { icon: "linkedin", link: "https://www.linkedin.com/company/meson-network"}
  - { icon: "rss-square", link: "/feed.xml" }
# - {icon: 'rss-square', link: '/rss-feed.xml'}
